# Generated by Django 4.2.3 on 2023-10-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_remove_contact_date_contact_evaluator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='url',
        ),
        migrations.AddField(
            model_name='contact',
            name='url',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='Customer.url'),
        ),
    ]
