# Generated by Django 4.2.3 on 2023-10-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_url_remove_contact_evaluator_remove_contact_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='url',
            new_name='urls',
        ),
    ]
