# Generated by Django 4.2.3 on 2023-10-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_url_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='urls',
        ),
        migrations.AddField(
            model_name='contact',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='URL',
        ),
    ]
