# Generated by Django 4.2.3 on 2023-10-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_contact_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='custom_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
