# Generated by Django 4.2.3 on 2023-10-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_remove_contact_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='abc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
