# Generated by Django 4.2.3 on 2023-10-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_contact_abc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='abc',
        ),
    ]
