# Generated by Django 4.2.3 on 2023-10-15 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_remove_contact_abc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
