# Generated by Django 4.2.3 on 2023-10-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0016_alter_contact_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='custom_id',
        ),
    ]
