# Generated by Django 4.2.3 on 2023-10-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0017_remove_contact_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='url',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='webName',
        ),
    ]
