# Generated by Django 4.2.3 on 2023-10-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0019_contact_desc_contact_email_contact_name_contact_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
