# Generated by Django 4.2.3 on 2023-10-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website_name', models.CharField(max_length=100)),
                ('website_url', models.URLField()),
            ],
        ),
    ]
