# Generated by Django 4.2.3 on 2023-10-25 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0002_forwardeddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forwardeddata',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='forwardeddata',
            name='due_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
