# Generated by Django 4.2.3 on 2023-10-28 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0007_alter_user_job_position'),
        ('Evaluator', '0003_rename_name_forwardeddata_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_url', models.URLField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAdmin.user')),
            ],
        ),
    ]
