# Generated by Django 4.2.3 on 2023-11-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0007_facialexpression'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detected_faces/')),
                ('bounding_box_x', models.IntegerField()),
                ('bounding_box_y', models.IntegerField()),
                ('bounding_box_width', models.IntegerField()),
                ('bounding_box_height', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Detected Faces',
            },
        ),
    ]
