# Generated by Django 4.2.3 on 2023-11-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0008_detectedface'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('Angry', 'Angry'), ('Disgust', 'Disgust'), ('Fear', 'Fear'), ('Happy', 'Happy'), ('Sad', 'Sad'), ('Surprise', 'Surprise'), ('Neutral', 'Neutral')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
