# Generated by Django 4.2.1 on 2023-11-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0009_emotionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='GazeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaze_x', models.FloatField()),
                ('gaze_y', models.FloatField()),
                ('head_x', models.FloatField()),
                ('head_y', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
