# Generated by Django 4.2.3 on 2023-12-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0011_eyetrackingdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyetrackingdata',
            name='data',
        ),
        migrations.AddField(
            model_name='eyetrackingdata',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
