# Generated by Django 4.2.1 on 2024-01-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0013_emotionrecord_user_id_alter_emotionrecord_emotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_image', models.BinaryField()),
            ],
        ),
    ]
