# Generated by Django 4.2.1 on 2024-01-20 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0014_emotiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardeddata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
