# Generated by Django 4.2.1 on 2024-01-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0015_alter_forwardeddata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotiondata',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Evaluator.forwardeddata'),
        ),
        migrations.AlterField(
            model_name='emotiondata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forwardeddata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
