# Generated by Django 4.2.1 on 2024-01-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0017_alter_forwardeddata_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectedFace',
        ),
        migrations.RenameField(
            model_name='emotiondata',
            old_name='id',
            new_name='projectid',
        ),
        migrations.AddField(
            model_name='emotiondata',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emotiondata',
            name='website_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emotiondata',
            name='website_url',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='EmotionRecord',
        ),
    ]
