# Generated by Django 4.2.1 on 2024-02-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0018_delete_detectedface_rename_id_emotiondata_projectid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pie_chart_image', models.BinaryField()),
            ],
        ),
    ]
