# Generated by Django 4.2.3 on 2023-10-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0005_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jobPosition',
            new_name='job_position',
        ),
    ]
