# Generated by Django 4.2.3 on 2023-10-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0006_rename_jobposition_user_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
