# Generated by Django 4.2.3 on 2023-11-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0007_alter_user_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
