# Generated by Django 4.2.3 on 2023-11-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0008_alter_user_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyAdmin.user'),
        ),
    ]
